insert into author(fname, lname) values('Jack', 'Miller');
insert into author(fname, lname) values('Eric', 'Becker');
insert into author(fname, lname) values('Stephanie', 'Wiley');
insert into author(fname, lname) values('Laura', 'Thompson');
insert into author(fname, lname) values('David', 'Diamond');
insert into author(fname, lname) values('Alison', 'Fowler');
insert into author(fname, lname) values('Karen', 'Evans');

insert into book(title) values('The Art of Programming');
insert into book(title) values('A World of 3D Printed Wonders');
insert into book(title) values('Beyond the Limits of Robotics');
insert into book(title) values('Cybersecurity Threats and Solutions');
insert into book(title) values('The Future of Computing');
insert into book(title) values('Efficient Algorithms');
insert into book(title) values('Protecting the Digital World');
insert into book(title) values('Unlocking Unlimited Energy');
insert into book(title) values('Advancing Science and Innovation');
insert into book(title) values('The Next Evolution of the Web');
insert into book(title) values('Designing for the User');
insert into book(title) values('A Guide to Building Intelligent Systems');
insert into book(title) values('Finding and Fixing Software Bugs');
insert into book(title) values('A Guide to Mastery in Any Programming Language');
insert into book(title) values('Sustainability in the Digital Age');
insert into book(title) values('Connecting Everything, Everywhere');

insert into auth_book(aid, bid) values (3, 1);
insert into auth_book(aid, bid) values (7, 1);
insert into auth_book(aid, bid) values (2, 2);
insert into auth_book(aid, bid) values (3, 3);
insert into auth_book(aid, bid) values (1, 4);
insert into auth_book(aid, bid) values (5, 4);
insert into auth_book(aid, bid) values (6, 4);
insert into auth_book(aid, bid) values (1, 5);
insert into auth_book(aid, bid) values (6, 6);
insert into auth_book(aid, bid) values (6, 7);
insert into auth_book(aid, bid) values (7, 8);
insert into auth_book(aid, bid) values (3, 9);
insert into auth_book(aid, bid) values (5, 11);
insert into auth_book(aid, bid) values (7, 11);
insert into auth_book(aid, bid) values (7, 12);
insert into auth_book(aid, bid) values (6, 13);
insert into auth_book(aid, bid) values (3, 14);
insert into auth_book(aid, bid) values (1, 14);
insert into auth_book(aid, bid) values (3, 15);